name: dockerfile checks

on: push

jobs:
  dockerfile-check:
    name: Check Dockerfile
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Lint
        run: |
          cd kudu-aarch64
          docker run --rm -i hadolint/hadolint < Dockerfile
