name: Test build on Huaweicloud swr

on: push

env:
  ACCESS_KEY_ID: ${{ secrets.ACCESS_KEY_ID }}
  SECRET_ACCESS_KEY: ${{ secrets.SECRET_ACCESS_KEY }}
  REGION: "ap-southeast-3"
  PROJECT_ID: "c847fb717563484fa95d18a75ae7831c"
  CLUSTER_ID: "0803769d-8dd3-11eb-9282-0255ac1001e6"

  ALLUXIO_IMG: ghcr.io/liusheng/alluxio-aarch64
  DEPLOYMENT_NAME: alluxio-deployment

jobs:
  huaweicloud-swr:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      # 1.1 (optional) login to SWR and upload customized image
      - uses: liusheng/swr-login@v0.0.1
        with:
          region: "${{ env.REGION }}"
          access-key-id: "${{ env.ACCESS_KEY_ID }}"
          access-key-secret: "${{ env.SECRET_ACCESS_KEY }}"

      # 1.2 (optional) Build and push image to ACR
#      - name: Build and push image to ACR
#        run: |
#           docker pull ghcr.io/liusheng/xxx
#          docker build --tag "$REGISTRY/$NAMESPACE/$IMAGE:$TAG" .
#          docker push "$REGISTRY/$NAMESPACE/$IMAGE:$TAG"

      - name: Get kubectl
        run: |
          curl -sL https://dl.k8s.io/v1.15.11/kubernetes-client-linux-amd64.tar.gz | tar zx -C $HOME/
          export PATH=PATH:$HOME/kubernetes/client/bin

      - uses: liusheng/cce-context@v1
        with:
          region: "${{ env.REGION }}"
          access-key-id: "${{ env.ACCESS_KEY_ID }}"
          access-key-secret: "${{ env.SECRET_ACCESS_KEY }}"
          project-id: "${{ env.PROJECT_ID }}"
          cluster-id: "${{ env.CLUSTER_ID }}"

      # Deploy the image to the CCE cluster
      - name: Set up Kustomize
        run: |-
          curl -s "https://raw.githubusercontent.com/kubernetes-sigs/kustomize/master/hack/install_kustomize.sh"  | bash /dev/stdin 4.0.5

      - name: Deploy
        run: |-
          kubectl config use-context external
          kubectl get all
#          touch kustomization.yaml
#          ./kustomize edit set image "REGISTRY/NAMESPACE/IMAGE:TAG=${ALLUXIO_IMG}:latest"
#          ./kustomize build . | kubectl apply -f -
#          kubectl rollout status deployment/${DEPLOYMENT_NAME}
#          kubectl get services -o wide