name: Test build on Huaweicloud swr

on: push

env:
  ACESS_KEY_ID: ${{ secrets.ACESS_KEY_ID }}
  SECRET_ACCESS_KEY: ${{ secrets.SECRET_ACCESS_KEY }}
  REGION: ap-southeast-3
  KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}
  ALLUXIO_IMG: ghcr.io/liusheng/alluxio-aarch64
  DEPLOYMENT_NAME: alluxio-deployment

jobs:
  huaweicloud-swr:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Login to SWR
        run: |
          docker login -u "${REGION}@${ACESS_KEY_ID}" -p "${SECRET_ACCESS_KEY}" "swr.${REGION}.myhuaweicloud.com"

      - name: Get kubectl
        run: |
          curl -sL https://dl.k8s.io/v1.15.11/kubernetes-client-linux-amd64.tar.gz | tar zx -C $HOME/
          export PATH=PATH:$HOME/kubernetes/client/bin

      - name: Get K8S cluster config
        run: |
          kubectl version
          mkdir -p $HOME/.kube
          echo ${KUBE_CONFIG} > $HOME/.kube/config
          export KUBECONFIG=~/.kube/config
          kubectl config use-context external
          kubectl cluster-info

      # 3.2 Deploy the image to the ACK cluster
      - name: Set up Kustomize
        run: |-
          curl -s "https://raw.githubusercontent.com/kubernetes-sigs/kustomize/master/hack/install_kustomize.sh"  | bash /dev/stdin 3.8.6

      - name: Deploy
        run: |-
          ./kustomize edit set image REGISTRY/NAMESPACE/IMAGE:TAG=${ALLUXIO_IMG}:latest
          ./kustomize build . | kubectl apply -f -
          kubectl rollout status deployment/${DEPLOYMENT_NAME}
          kubectl get services -o wide